baseurl = "http://saa.ninja/"
languageCode = "en-us"
title = "saa.ninja"
theme = "hyde"

[author]
    name = "Sergey Abramyan"

[permalinks]
    post = "/blog/:title/"

[indexes]
    category = "categories"

[taxonomies]
    tag = "tags"
    series = "series"
    series-desc = "series-desc"

[params]
    copyright = "Sergey Abramyan"
    description = "Sergey Abramyan"
    twitter = "https://twitter.com/sabramyan"
    github = "https://github.com/saa"
